# Generated by Django 5.2.7 on 2025-10-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('probably', 'Probably'), ('probably_not', 'Probably Not'), ('dont_know', "Don't Know")], max_length=20)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akinator_app.character')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akinator_app.question')),
            ],
        ),
    ]
