# Generated by Django 5.2.7 on 2025-10-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinator_app', '0002_character_description_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
