# Generated by Django 5.2.7 on 2025-10-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinator_app', '0003_remove_character_character_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='asked_question_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='candidate_character_ids',
            field=models.JSONField(default=list),
        ),
    ]
