# Generated by Django 5.2.7 on 2025-10-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akinator_app', '0004_gamesession_asked_question_ids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='candidate_character_ids',
            new_name='possible_character_ids',
        ),
    ]
