# Generated by Django 5.2.7 on 2025-10-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinator_app', '0005_rename_candidate_character_ids_gamesession_possible_character_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contradictory_questions',
            field=models.ManyToManyField(blank=True, to='akinator_app.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='prerequisite_questions',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='akinator_app.question'),
        ),
    ]
